# -*- coding: utf-8 -*-
"""Code_20951061.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4qI2jKQwo2sKgRmmdKpVVmTFx0Lq9vh
"""

import numpy as np
import pandas as pd

if __name__ == '__main__':
    from google.colab import drive
    drive.mount('/content/drive')
    training_data = pd.read_csv('/content/drive/MyDrive/COMP4211/pa1/dataset/train.csv', delimiter=',')
    testing_data = pd.read_csv('/content/drive/MyDrive/COMP4211/pa1/dataset/test.csv', delimiter=',')

"""**Part 1: Data Exploration and Preparation**

Load the provided train.csv file using pandas. Write code to perform an initial data exploration
to understand the basic statistics about all the attributes and target variables. Although you
need to run the code to explore this dataset, you need to answer the questions [Q1] to [Q6] on
the training set. Your report should include:

[Q1] Dataset Overview.

• Size of the Dataset: Total number of instances and features.

• Feature Types: Identify numerical and categorical features.
"""

# @title
training_data.info()
print("Training data: \nInstance: {} , Feature: {}".format(training_data.shape[0], training_data.shape[1]))
print("Testing data: \nInstance: {} , Feature: {}".format(testing_data.shape[0], testing_data.shape[1]))

"""[Q2] Missing Values.

• Identification: Report any features with missing values and the proportion of missing
values for them.

• Potential Impact: Briefly discuss how these missing values might affect analysis and
model performance.

"""

print("features with missing values:")
print(training_data.isnull().sum())

print("---------------------------------------------------------------------------")
print("proportion of missing values:")
print(training_data.isnull().sum() /len(training_data))

"""[Q3] Feature Distribution.

• Numerical Features: Identify which ones are discrete or continuous. Describe the dis-
tribution (i.e., mean, median, range, standard deviation) of all numerical features, and
visualize the distribution of one of the numerical features using a box plot.

• Categorical Features: Identify which ones are binary, nominal, or ordinal. Select 2 of
the categorical features, summarize the count of categories for each, and visualize their
distributions using bar plots.
"""

numerical_training_data = training_data.select_dtypes(include=['int64', 'float64'])
numerical_training_data.describe()

import matplotlib.pyplot as plt
import seaborn as sns

chosen_feature = "SleepHours"
plt.figure(figsize=(10, 6))
sns.boxplot(x=chosen_feature, data=training_data)
plt.title('Box Plot')
plt.show()

chosen_feature = "GeneralHealth"
training_data[chosen_feature].value_counts()

plt.figure(figsize=(10, 6))
sns.countplot(x=chosen_feature, data=training_data)
plt.title('Bar Plot')
plt.show()

chosen_feature = "PhysicalActivities"
training_data[chosen_feature].value_counts()

plt.figure(figsize=(10, 6))
sns.countplot(x=chosen_feature, data=training_data)
plt.title('Bar Plot')
plt.show()

"""[Q4] Correlation Analysis.

• Feature Correlation: Visualize the correlation between every two features (numerical
features only, including the regression targets) with a heatmap. You can use matplotlib
and seaborn to help you.

• Insights: Highlight any strong correlations that might influence feature selection or ne-
cessitate feature engineering.
"""

numerical_training_data.corr()

plt.figure(figsize=(10, 6))
sns.heatmap(numerical_training_data.corr(), annot=True, cmap='YlGnBu', linecolor='r', linewidths=0.5)
plt.title('Heat Map')
plt.show()

"""[Q5] Handling Missing Values

Apply SimpleImputer to handle missing values.

Briefly dis-cuss its impact on feature distribution and model performance.

Briefly discuss what imputation strategies (mean, median, mode, and constant) should be used for what reasons.
"""

from sklearn.impute import SimpleImputer

impute = SimpleImputer(strategy='median')
numerical_training_data_imputed = pd.DataFrame(impute.fit_transform(numerical_training_data), columns=numerical_training_data.columns)
numerical_training_data_imputed

"""[Q6] Normalization and Standardization:

Normalize/standardize different types of numerical features using StandardScaler, MinMaxScaler, or RobustScaler.

You need to report the first numerical feature column of the first 10 samples before and after processing.

Briefly discuss the difference between these techniques and when to use each.

"""

numerical_training_data_imputed.iloc[:10, 0]
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()
robust_scaler = RobustScaler()

numerical_training_data_standard = pd.DataFrame(standard_scaler.fit_transform(numerical_training_data_imputed), columns=numerical_training_data_imputed.columns)
numerical_training_data_minmax = pd.DataFrame(minmax_scaler.fit_transform(numerical_training_data_imputed), columns=numerical_training_data_imputed.columns)
numerical_training_data_robust = pd.DataFrame(robust_scaler.fit_transform(numerical_training_data_imputed), columns=numerical_training_data_imputed.columns)

print("Before Processing:")
numerical_training_data_imputed.iloc[:10, 0]

print("Standard:")
numerical_training_data_standard.iloc[:10, 0]

print("Minmax:")
numerical_training_data_minmax.iloc[:10, 0]

print("Robust:")
numerical_training_data_robust.iloc[:10, 0]

"""[Q7] Encoding Categorical Variables:

Utilize OneHotEncoder and OrdinalEncoder to encode different types of categorical variables.

For certain ordinal feature(s), a direct application of
the OrdinalEncoder may lead to a suboptimal ranking between categories.

You need to handle this by adjusting the settings within the OrdinalEncoder.

Additionally, you need to report the entire table in the jupyter notebook, showing the first 10 samples before and after processing in pandas.DataFrame structure.

Briefly explain the scenarios where each encoding technique is
preferred.

"""

categorical_training_data = training_data.select_dtypes(include=['object', 'category']).columns.tolist()
print("Before Processing:")
training_data_extracted = training_data.select_dtypes(include=['object', 'category'])[:10]
training_data_extracted

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

print("After Processing:")
one_hot_encoder = OneHotEncoder(sparse_output=False, drop=None)
one_hot_encoded = one_hot_encoder.fit_transform(training_data[categorical_training_data])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=one_hot_encoder.get_feature_names_out(categorical_training_data))

ordinal_encoder = OrdinalEncoder()
ordinal_encoded = ordinal_encoder.fit_transform(training_data[categorical_training_data])
ordinal_df = pd.DataFrame(ordinal_encoded, columns=ordinal_encoder.get_feature_names_out(categorical_training_data))

ordinal_training_data = {
    'LastCheckupTime':['Within past year (anytime less than 12 months ago)',
                       '1 year but less than 2 years ago (Within past 2 years)',
                       '2 year but less than 5 years ago (Within past 5 years)',
                       '5 or more years ago'
                      ],
    'RemovedTeeth':['0', '1 to 5', '6 or more, but not all', 'All'],
    'GeneralHealth':['Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
    'ECigaretteUsage':['Never used e-cigarettes in my entire life',
                       'Not at all (right now)',
                       'Use them a few days',
                       'Use them every day'
                       ],
    'others':['No', 'Yes']
}
optimal_ordinal_encoder = OrdinalEncoder(categories=[ordinal_training_data[i] for i in ordinal_training_data])
optimal_ordinal_encoded = ordinal_encoder.fit_transform(training_data[categorical_training_data])
optimal_ordinal_df = pd.DataFrame(ordinal_encoded, columns=ordinal_encoder.get_feature_names_out(categorical_training_data))

print("OneHotEncoder:")
one_hot_df[:10]

print("OrdinalEncoder:")
ordinal_df[:10]

print("Optimal OrdinalEncoder:")
optimal_ordinal_df[:10]

"""[Q8] Feature Selection:

Perform feature selection with either feature selection modules in scikit-learn, such as SelectKBest, or based on the correlation analysis on all features (including numerical and categorical features) similar to [Q5].

Think about how feature selection impacts the performance of your models.

You need to report which features were removed for what reasons
"""

from sklearn.feature_selection import SelectKBest, f_classif

combined_df = pd.concat([optimal_ordinal_df, numerical_training_data_minmax.iloc[:, :-2]],axis=1)

selector = SelectKBest(score_func=f_classif, k=26)
training_data_selected = selector.fit_transform(combined_df,training_data.iloc[:, -2:-1])
selected_features = selector.get_support(indices=True)
score = pd.DataFrame({'Feature':combined_df.columns, 'Score': selector.scores_}).sort_values(by='Score', ascending=False)
score

"""In this task, you will build multiple linear regression models in the first step, where each model uses only one feature to determine its correlation with the regression target (the second last column ‘Age’). In this stage, you only need to focus on binary categorical and continuous numerical features."""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import time

first_step_result = pd.DataFrame(columns=['Feature', 'R2', 'MSE', 'Time'])

non_binary_catagorical = ['RaceEthnicityCategory', 'SmokerStatus', 'LastCheckupTime', 'RemovedTeeth', 'GeneralHealth', 'ECigaretteUsage']

binary_and_numerical_selected = combined_df.columns.tolist()
for i in non_binary_catagorical:
  binary_and_numerical_selected.remove(i)

selected = combined_df.columns[selected_features].tolist()
binary_and_numerical_selected = list(set(binary_and_numerical_selected) & set(selected))
print(binary_and_numerical_selected)

for i in binary_and_numerical_selected:
  X = combined_df[i]
  Y = numerical_training_data_minmax['Age']
  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
  model = LinearRegression()
  X_train = np.array(X_train).reshape(-1, 1)
  X_test = np.array(X_test).reshape(-1, 1)
  starting_time = time.time()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  ending_time = time.time()
  training_time = ending_time - starting_time
  r2 = r2_score(y_test, y_pred)
  mse = mean_squared_error(y_test, y_pred)
  temp_result = pd.DataFrame({'Feature': [i], 'R2': [r2], 'MSE': [mse], 'Time': [training_time]})
  first_step_result = pd.concat([first_step_result, temp_result], ignore_index=True)

#first_step_result

"""

Then, in the second step, you will build another linear regression model using the features that yield the best performance in your experiment to explore their relationship with the regression target.

You are required to use the train test split submodule in scikit-learn to split the data in train.csv, with 80% for training and 20% for validation. You should set random state = 4211 for reproducibility.

"""

best_feature = first_step_result.nlargest(15, 'R2')['Feature'].tolist()
second_step_result = pd.DataFrame(columns=['Feature', 'R2', 'MSE', 'Time'])


X = combined_df[best_feature]
Y = numerical_training_data_minmax['Age']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
model = LinearRegression()
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
temp_result = pd.DataFrame({'Feature': 'Best Feature', 'R2': [r2], 'MSE': [mse], 'Time': [training_time]})
second_step_result = pd.concat([second_step_result, temp_result], ignore_index=True)

#second_step_result

"""[Q9] After training multiple models described above using the training set, use them to make predictions on the validation set. Report the validation R2 score of each of the models to evaluate the relationship between different features and the regression target.


"""

all_model = pd.concat([first_step_result, second_step_result], ignore_index=True)
all_model[['Feature','R2']]

"""[Q10] Report the mean squared error of each of the models in the validation set and compare them based on the two performance metrics, i.e., R2 score and Mean Squared Error (MSE).


"""

all_model = pd.concat([first_step_result, second_step_result], ignore_index=True)
all_model[['Feature','MSE']]

"""[Q11] Discuss the mathematical meaning of the weight (in brief) for a binary categorical in-dependent variable. How can a nominal categorical feature with more than 2 possible values be formulated as the independent variable of a linear model? Include the necessary component of the nominal categorical features alongside the previously selected features to enhance the model’s performance compared to [Q9-Q10]. Report the validation R2 score and MSE of this linear regression model."""

enhance_result = pd.DataFrame(columns=['Feature', 'R2', 'MSE', 'Time'])
X = combined_df
Y = numerical_training_data_minmax['Age']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
model = LinearRegression()
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
temp_result = pd.DataFrame({'Feature': 'enhanced', 'R2': [r2], 'MSE': [mse], 'Time': [training_time]})
enhance_result = pd.concat([enhance_result, temp_result], ignore_index=True)

enhance_result

"""In this part, you are asked to use the features selected in Section 6.1 to train feedforward neural networks.

You need to try different numbers of hidden units H ∈ {1, 8, 32, 128} to build different three-hidden-layer neural networks. The hyperparameter early stopping can be set to ‘True’ to avoid overfitting (default is ‘False’). The other hyperparameters may just take their default values. For each hidden layer in a specific neural network model, the number of hidden units should be kept the same for simplicity. During training, you are expected to record the training time of each model. After training, evaluate your models by reporting the R2 scores on the validation set. You have to report the R2 score for each value of H by plotting them using matplotlib.




"""

from sklearn.neural_network import MLPRegressor

hidden_units = [1,8,32,128]

feed_forward_result = pd.DataFrame(columns=['H', 'R2', 'MSE', 'Time'])

for H in hidden_units:
  X = combined_df
  Y = numerical_training_data_minmax['Age']
  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
  model = MLPRegressor(hidden_layer_sizes=(H,H,H), early_stopping=True)
  starting_time = time.time()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  ending_time = time.time()
  training_time = ending_time - starting_time
  r2 = r2_score(y_test, y_pred)
  mse = mean_squared_error(y_test, y_pred)
  temp_result = pd.DataFrame({'H': [H], 'R2': [r2], 'MSE': [mse], 'Time': [training_time]})
  feed_forward_result = pd.concat([feed_forward_result, temp_result], ignore_index=True)

feed_forward_result

plt.figure(figsize=(10, 6))
plt.plot(hidden_units, feed_forward_result['R2'], marker='o')
plt.title('R2 Scores for Different Numbers of Hidden Units')
plt.xlabel('Number of Hidden Units (H)')
plt.ylabel('R2 Score')
plt.xticks(hidden_units)
plt.grid()
plt.show()

"""[Q12] Report the model setting, training time, and performance of the neural network model for each value of H. You are also expected to repeat each setting three times for the same hyperparameter setting and report the mean and standard deviation of the training time, R2 and MSE score for each setting.


"""

feed_forward_result

"""[Q13] Compare the training time and R2 score of the linear regression model and the best neural network model.


"""

print('feed forward:')
feed_forward_result[['H', 'R2', 'Time']]

print('linear regression model:')
enhance_result[['Feature', 'R2', 'Time']]

"""[Q14] Do you notice any trend of R2 and MSE score when you increase the hidden layer size from
1 to 128? Explain the difference between the two metrics in evaluating regression models.
"""

#haha hehe lala

"""In this task, you will build a logistic regression model as well as neural network classifiers to predict whether or not the classification target ‘HadHeartAttack’ is ‘true’. You are also required to use the train test split submodule in scikit-learn to split the data, with 80% for training and 20% for validation. As before, we ask that you set random state = 4211 for reproducibility.

Learning of the logistic regression model should use a gradient-descent algorithm by minimizing the cross-entropy loss. It requires that the step size parameter η be specified. Try out a few values (<1) and choose one that leads to stable convergence. You may also decrease η gradually during the learning process to enhance convergence. When set properly, this can be done automatically in scikit-learn. Use the features selected in [Q10] to train the model. During training, record the training time for the logistic regression model. After training, you are required to evaluate your model using accuracy and the F1 score on the validation set. Please be careful to choose the built-in models that are suitable for your tasks, i.e., the default setting of sklearn.linear model.LogisticRegression is not a correct choice for our logistic regression model since it does not use gradient descent.
"""

from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

best_feature = first_step_result.nlargest(15, 'R2')['Feature'].tolist()
Logistic_result = pd.DataFrame(columns=['Feature', 'Accuracy', 'F1', 'Time'])


X = combined_df[binary_and_numerical_selected]
Y = numerical_training_data_minmax['HadHeartAttack']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
model = SGDClassifier(learning_rate='optimal', eta0=0.01, loss="log_loss", max_iter=100, penalty ='l2')
#model = LogisticRegression()
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Feature': 'Feature in Q10', 'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
Logistic_result = pd.concat([Logistic_result, temp_result], ignore_index=True)

"""[Q15] Report the model setting, training time, and performance of the logistic regression model. Since the solution found may depend on the initial weight values, you are expected to repeat each setting three times and report the corresponding mean and standard deviation of the training time, accuracy, and the F1 score for each setting.


"""

Logistic_result

"""[Q16] Plot the ROC curve calculated on the validation set with the last model in [Q15] and report the AUC value.


"""

from sklearn.metrics import roc_curve, auc

y_pred_proba = model.predict_proba(X_test)[:,1]
fpr, tpr, _ = roc_curve(y_test,  y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.0])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc='lower right')
plt.show()

"""[Q17] Report the number of true positive, true negative, false positive, and false negative on the validation set with the last model in [Q15]. Discuss why these numbers are helpful in comparison to solely relying on the F1 score, especially on the healthcare dataset."""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]
print('True Positive: ', TP, '\nTrue Negative: ' , TN,'\nFalse Positive: ', FP,'\nFalse Negative: ', FN)

"""Neural network classifiers generalize logistic regression by introducing one or more hidden layers. Their learning algorithm is similar to that for logistic regression, as described above. Remember to standardize the features before training and validation.

You need to try different numbers of hidden units H ∈ {1, 8, 32, 128} to build different three-hidden-layer neural networks. The hyperparameter early stopping can be set to ‘True’ to avoid overfitting (default is ‘False’). The other hyperparameters may just take their default values. During training, you are expected to record the training time of each model. After training, evaluate your models using accuracy and the F1 score on the validation set. You have to report the accuracy and F1 score for each value of H by plotting them using matplotlib.
"""

from sklearn.neural_network import MLPClassifier

hidden_units = [1,8,32,128]

feed_forward_result = pd.DataFrame(columns=['H', 'Accuracy', 'F1', 'Time'])

roc_auc_lst = []

for H in hidden_units:
  X = combined_df
  Y = numerical_training_data_minmax['HadHeartAttack']
  X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
  model = MLPClassifier(hidden_layer_sizes=(H,H,H), early_stopping=True)
  starting_time = time.time()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  ending_time = time.time()
  training_time = ending_time - starting_time
  accuracy = accuracy_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  temp_result = pd.DataFrame({'H': [H], 'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
  feed_forward_result = pd.concat([feed_forward_result, temp_result], ignore_index=True)

  y_pred_proba = model.predict_proba(X_test)[:,1]
  fpr, tpr, _ = roc_curve(y_test,  y_pred_proba)
  tmp = {'H':H, 'fpr':fpr, 'tpr':tpr, 'roc_auc':auc(fpr, tpr)}
  roc_auc_lst.append(tmp)

feed_forward_result

"""[Q18] Report the model setting, training time, and performance of the neural networks for each value of H. You are also expected to repeat each setting three times and report the mean and standard deviation of the training time, accuracy, and the F1 score for each setting."""

feed_forward_result['Time']

"""[Q19] Plot the accuracy and F1 score for each value of H. Suggest a possible reason for the gap between the accuracy and F1 score."""

fig, axs = plt.subplots(1,2)
fig.set_size_inches([20,5])

r2_list = []
for i,ax in enumerate(axs.flat):
    ax.scatter(feed_forward_result['H'], feed_forward_result[feed_forward_result.columns[i+1]])
    ax.set_title(f'H against {feed_forward_result.columns[i+1]}')
    ax.set(ylabel= feed_forward_result.columns[i+1] ,xlabel="H")

plt.show()

"""[Q20] Compare the training time, accuracy, and the F1 score of the logistic regression model and the best neural network model."""

print('logistic regression model:')
Logistic_result

print('neural network model:')
feed_forward_result

"""[Q21] Do you notice any trend when you increase the hidden layer size from 1 to 128? If so, please describe what the trend is and suggest a reason for your observation."""

#haha hehe lala

"""[Q22] Plot the ROC curve calculated on the validation set with the hidden layer size of 1 and the hidden layer size of 128. Give one reason why we need to examine the ROC curve as well."""

for tmp in roc_auc_lst[::3]:
  plt.figure()
  plt.plot(tmp['fpr'], tmp['tpr'], color='blue', lw=2, label=f'ROC curve (area = {tmp["roc_auc"]:.2f})')
  plt.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--')
  plt.xlim([0.0, 1.0])
  plt.ylim([0.0, 1.0])
  plt.xlabel('False Positive Rate')
  plt.ylabel('True Positive Rate')
  plt.title('Receiver Operating Characteristic H='+str(tmp['H']))
  plt.legend(loc='lower right')
  plt.show()

"""In this task, you will build a logistic regression model as well as neural network classifiers to predict whether or not the classification target ‘HadHeartAttack’ is ‘true’. You are also required to use the train test split submodule in scikit-learn to split the data, with 80% for training and 20% for validation. As before, we ask that you set random state = 4211 for reproducibility. This section aims to demonstrate the impact of different preprocessing techniques on model performance by constructing and evaluating multiple pipelines. This task is designed to provide hands-on experience with sklearn’s Pipeline and ColumnTransformer utilities, enabling efficient experimentation with various preprocessing strategies. You could use Pipeline to create a sequence of preprocessing steps for numerical and categorical data separately. Then, ColumnTransformer could be used to apply the respective pipelines to your dataset’s numerical and categorical columns. Your task is to evaluate how different preprocessing combinations affect the performance of three-hidden-layer neural networks to predict whether or not the target ‘HadHeartAttack’is true.

[Q23] Combination A: For numerical features, apply SimpleImputer with mean strategy for imputation. For categorical features, use OneHotEncoder for encoding. Normalize all features with StandardScaler. Do not apply feature selection and feature engineering. Validate this combination with a neural network model.
"""

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

combination_a = pd.DataFrame(columns=['Accuracy', 'F1', 'Time'])

X = training_data.drop('HadHeartAttack', axis=1)
Y = training_data['HadHeartAttack']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder()),
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(hidden_layer_sizes=(32,32,32), early_stopping=True))
])
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
combination_a = pd.concat([combination_a, temp_result], ignore_index=True)

combination_a

"""[Q24] Combination B: For numerical features, use StandardScaler for normalization and SimpleImputer with zero strategy for imputation. For categorical features, encode ordinal fea-tures with OrdinalEncoder and remaining with OneHotEncoder. Do not apply feature selection and feature engineering. Validate this combination with a neural network model."""

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

combination_b = pd.DataFrame(columns=['Accuracy', 'F1', 'Time'])

X = training_data.drop('HadHeartAttack', axis=1)
Y = training_data['HadHeartAttack']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
ordinal_features = X[['LastCheckupTime', 'RemovedTeeth', 'GeneralHealth', 'ECigaretteUsage']].columns.tolist()
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('imputer', SimpleImputer(strategy='constant', fill_value=0))

])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder()),
])
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder()),
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_features),
    ])
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(hidden_layer_sizes=(32,32,32), early_stopping=True))
])
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
combination_b = pd.concat([combination_b, temp_result], ignore_index=True)

combination_b

"""[Q25] Combination C: Create a custom combination where you choose a different preprocess-ing technique for numerical and categorical features based on your hypothesis of what might work best. This could also involve custom encoders, any appropriate feature selection, or engineering techniques. Validate this combination with a neural network model."""

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

combination_c = pd.DataFrame(columns=['Accuracy', 'F1', 'Time'])

X = training_data.drop('HadHeartAttack', axis=1)
Y = training_data['HadHeartAttack']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
ordinal_features = X[['LastCheckupTime', 'RemovedTeeth', 'GeneralHealth', 'ECigaretteUsage']].columns.tolist()
numerical_transformer = Pipeline(steps=[
    ('scaler', RobustScaler()),
    ('imputer', SimpleImputer(strategy='median'))

])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder()),
])
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder()),
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_features),
    ])
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(hidden_layer_sizes=(32,32,32), early_stopping=True))
])
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
combination_c = pd.concat([combination_c, temp_result], ignore_index=True)

combination_c

"""In this task, you need to use grid search to tune the hyperparameters of a three-hidden-layer feedforward neural network model to predict whether or not the target ‘HadHeartAttack’ is true. All the hyperparameters defined in the MLPClassifier class in scikit-learn except the number of hidden layers can be tuned. Use the best preprocessing techniques in [Q24] and features selected in [Q10] for training and testing.

You are required to use the model selection submodule in scikit-learn to facilitate perform-ing grid search cross-validation for hyperparameter tuning. This is done by randomly sampling 80% of the training instances to train a classifier and then validating it on the remaining 20%. Five such random data splits are performed and the average over these five trials is used to estimate the generalization performance. You are expected to try at least 10 combinations of the hyperparameter setting. Set the random state hyperparameter of the neural network model to 4211 for reproducibility and early stopping to ‘True’ to avoid overfitting.

[Q26] Report five combinations of the hyperparameter settings and highlight the best hyperpa-rameter setting in terms of validation accuracy. You also need to report the mean and standard deviation of the validation accuracy for the five random data splits for each hyperparameter setting. Finally, you need to evaluate the model with the best hyperparameter setting on the testing set and report the testing accuracy.
"""

from sklearn.model_selection import GridSearchCV

hyperparameter_tuning = pd.DataFrame(columns=['Best Parameter', 'Score', 'Accuracy', 'F1', 'Time'])

X = training_data[selected]
Y = training_data['HadHeartAttack']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4211)
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
ordinal_features = X[['LastCheckupTime', 'RemovedTeeth', 'ECigaretteUsage']].columns.tolist()
numerical_transformer = Pipeline(steps=[
    ('scaler', RobustScaler()),
    ('imputer', SimpleImputer(strategy='median'))

])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder()),
])
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder()),
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_features),
    ])
param_grid = {
    'classifier__hidden_layer_sizes': [(32,32), (64,)],
    'classifier__alpha': [0.0001, 0.001],
    'classifier__activation': ['relu', 'tanh', 'logistic'],
}
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(early_stopping=True))
])
grid_search = GridSearchCV(model, param_grid, cv=5, verbose=3)
grid_search.fit(X_train, y_train)

starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
best_params = grid_search.best_params_
best_score = grid_search.best_score_
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Best Parameter':[best_params], 'Score':[best_score], 'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
hyperparameter_tuning = pd.concat([hyperparameter_tuning, temp_result], ignore_index=True)

hyperparameter_tuning

Testing = pd.DataFrame(columns=['Accuracy', 'F1', 'Time'])

X_train = training_data[selected]
y_train = training_data['HadHeartAttack']
X_test = testing_data[selected]
y_test = testing_data['HadHeartAttack']
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
ordinal_features = X[['LastCheckupTime', 'RemovedTeeth', 'ECigaretteUsage']].columns.tolist()
numerical_transformer = Pipeline(steps=[
    ('scaler', RobustScaler()),
    ('imputer', SimpleImputer(strategy='median'))

])
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder()),
])
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder()),
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_features),
    ])
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', MLPClassifier(hidden_layer_sizes=(64,), alpha=0.001, activation='logistic', early_stopping=True))
])
model.fit(X_train, y_train)
starting_time = time.time()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
ending_time = time.time()
training_time = ending_time - starting_time
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
temp_result = pd.DataFrame({'Accuracy': [accuracy], 'F1': [f1], 'Time': [training_time]})
Testing = pd.concat([Testing, temp_result], ignore_index=True)

Testing